### ISSUE TITLE
error in 14.5.0

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/wifi#9]
``` wifi Error: Traceback (most recent call last):
File "/usr/local/munkireport/scripts/wifi", line 506, in
main()
File "/usr/local/munkireport/scripts/wifi", line 498, in main
result = merge_two_dicts(get_wifi_info(), known_networks)
File "/usr/local/munkireport/scripts/wifi", line 70, in get_wifi_info
info['bssid'] = format_mac_address(remove_all(' BSSID : ', line).strip())
File "/usr/local/munkireport/scripts/wifi", line 470, in format_mac_address
return mac_format.format(*tuple(mac_address.split(':')))
IndexError: Replacement index 1 out of range for positional args tuple
May 23 2024 15:15:15 +0100 WARNING: wifi return code: 1```

**Comment by tuxudo** [comment]
Resolved with version v3.7 of the module
